# Generated by Django 2.0.2 on 2018-03-21 08:08

from django.db import migrations, models
import imageupload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=imageupload.models.upload_to, verbose_name='Uploaded Image')),
                ('owner_id', models.CharField(default='00', max_length=50, null=True)),
                ('image_hash', models.CharField(default='00', max_length=50)),
            ],
        ),
    ]
